### PR TITLE
Test Zuul

### PR DESCRIPTION
**Pull request by rgarrigue**

### CODE REVIEW

**Comment by rgarrigue** [comment]
recheck

**Comment by sduthil** [comment]
From the [consul role docs](https://github.com/ansible-community/ansible-consul#requirements):
> To do so requires that unzip is available on the Ansible control host and the role will fail if it doesn't detect unzip in the PATH.

Any idea how to have `unzip` installed on the Zuul instance running Ansible? Is it Zuul itself or the worker?

**Comment by rgarrigue** [comment]
I added it to the base image https://github.com/TinxHQ/wazo-production-sf-config/commit/e2cd675b33dcba69e9754d421e45cd7d0ea47106

**Comment by rgarrigue** [comment]
recheck

**Comment by sduthil** [comment]
You did not want to merge the branch? Why not?

**Comment by rgarrigue** [comment]
My bad, I made so many branches with just a something changed in the README to test the CI, closed this one out of an habit.

**Pull request merged**
